{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "probe.name" . }}-secrets
  namespace: {{ include "probe.namespace" . }}
type: Opaque
stringData:
  FLEET_SECRET: {{ required "probe.head.fleetSecret is required" .Values.probe.head.fleetSecret | quote }}
{{- end }}
